version: "3"
services:
    terraria-server:
        image:  terraria-server
        volumes:
            - terraria_data:/opt/terraria/data
        ports:
            - 7777:7777/tcp
        restart: unless-stopped
        stop_grace_period: 30s
volumes: 
    terraria_data: ~
